apiVersion: v1
kind: Service
metadata:
  name: ${APP_NAME}
  namespace: ${APP_NAMESPACE}
  labels:
    app: ${APP_NAME}
spec:
  type: NodePort            # change to ClusterIP if you don't need a node port
  selector:
    app: ${APP_NAME}
  ports:
    - protocol: TCP
      port: ${APP_PORT}
      targetPort: ${APP_PORT}
      nodePort: ${NODE_PORT}
